version: '0.1.0'

index:
  name: user_index
  storage_type: hash
  prefix: users
  key_separator: ":"

fields:
  - name: user
    type: text
  - name: job
    type: text
  - name: credit_score
    type: tag
  - name: age
    type: numeric
  - name: user_embedding
    type: vector
    attrs:
      dims: 3
      datatype: float32
      algorithm: flat
      distance_metric: cosine
      initial_cap: 1000